### ISSUE TITLE
Interrupted test

### ISSUE THREAD

**Issue by jmonroynieto** [balzss/cli-typer#9]
CLI-typer uncaught exception terminates the session. I have not encountered this issue before. It only occurs with this file: 
[bb_words.txt](https://github.com/balzss/cli-typer/files/4136673/bb_words.txt)

I'm using MacOS mojave.

```
/Users/userx/cli-typer/app.js:61
    return text.replace(ANSI_ESCAPE, '');
                ^
├─────────────────────────────────────────────────────────────────────────────┤
TypeError: Cannot read property 'replace' of undefined
    at removeAnsiEscape (/Users/userx/cli-typer/app.js:61:17)
    at boxText (/Users/userx/cli-typer/app.js:81:36)
    at drawBox (/Users/userx/cli-typer/app.js:111:87)
    at ReadStream.<anonymous> (/Users/userx/cli-typer/app.js:334:5)
    at ReadStream.emit (events.js:210:5)
    at addChunk (_stream_readable.js:326:12)
    at readableAddChunk (_stream_readable.js:297:13)
    at ReadStream.Readable.push (_stream_readable.js:235:10)
    at TTY.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by ghost** [comment]
I have encountered the same issue. This is happening repeatedly with the below wordlist.

```
  Start typing the words below:

/usr/lib/node_modules/cli-typer/app.js:61
    return text.replace(ANSI_ESCAPE, '');
                ^
├─────────────────────────────────────────────────────────────────────────────┤
TypeError: Cannot read property 'replace' of undefined
    at removeAnsiEscape (/usr/lib/node_modules/cli-typer/app.js:61:17)
    at boxText (/usr/lib/node_modules/cli-typer/app.js:81:36)
    at drawBox (/usr/lib/node_modules/cli-typer/app.js:111:87)
    at ReadStream.<anonymous> (/usr/lib/node_modules/cli-typer/app.js:334:5)
    at ReadStream.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at ReadStream.Readable.push (_stream_readable.js:218:10)
    at TTY.onStreamRead (internal/stream_base_commons.js:188:23)
```

This time for this specific wordlist:
```
~
!
@
#
$
%
^
&
*
(
)
_
+
`
1
2
3
4
5
6
7
8
9
0
-
=
;
:
{
}
[
]
\
|
```

I hope the maintainer sees this and at least replies to this thread.

**Comment by jmonroynieto** [comment]
I don't think the issues are actively tended to.

The workaround is to increase the wordlist's length. This is easy enough to do with CLI utilities.
